var navelement1 = document.getElementById("navelement1")
        navelement1.onmouseover = function () {
            navelement1.innerHTML = "關於我們";
            navelement1.style.color = "red";
            navelement1.style.fontWeight = "bold"
            navelement1.style.fontSize = "24px"
            
        }
        navelement1.onmouseleave = function () {
            navelement1.innerHTML = "About Us";
            navelement1.style.color = "black";
            navelement1.style.fontWeight = "normal"
            navelement1.style.fontSize = "25px";

        }
        var navelement2 = document.getElementById("navelement2")
        navelement2.onmouseover = function () {
            navelement2.innerHTML = "報導";
            navelement2.style.color = "red";
            navelement2.style.fontWeight = "bold"
            navelement2.style.fontSize="25px"
            
            
        }
        navelement2.onmouseleave = function () {
            navelement2.innerHTML = "Report";
            navelement2.style.color = "black";
            navelement2.style.fontWeight = "normal"
            navelement2.style.fontSize = "25px";
            navelement2.style.padding = "0"


        }
        var navelement3 = document.getElementById("navelement3")
        navelement3.onmouseover = function () {
            navelement3.innerHTML = "精選甜品";
            navelement3.style.color = "red"
            navelement3.style.fontWeight = "bold"
            navelement3.style.fontSize = "21.2px"
        }
        navelement3.onmouseleave = function () {
            navelement3.innerHTML = "Products";
            navelement3.style.color = "black"
            navelement3.style.fontWeight = "normal"
            navelement3.style.fontSize = "25px";

        }
        var navelement4 = document.getElementById("navelement4")
        navelement4.onmouseover = function () {
            navelement4.innerHTML = "菜單";
            navelement4.style.color = "red";
            navelement4.style.fontWeight = "bold"
            navelement4.style.fontSize = "28.6px"
        }
        navelement4.onmouseleave = function () {
            navelement4.innerHTML = "Menu";
            navelement4.style.color = "black";
            navelement4.style.fontWeight = "normal"
            navelement4.style.fontSize = "25px";

        }
        var navelement5 = document.getElementById("navelement5")
        navelement5.onmouseover = function () {
            navelement5.innerHTML = "優惠活動";
            navelement5.style.color = "red";
            navelement5.style.fontWeight = "bold"
            navelement5.style.fontSize = "23.52px"
            navelement5.style.letterSpacing = "5px"
        }
        navelement5.onmouseleave = function () {
            navelement5.innerHTML = "Promotions";
            navelement5.style.color = "black";
            navelement5.style.fontWeight = "normal"
            navelement5.style.fontSize = "25px";
            navelement5.style.letterSpacing = "0px"

        }
        var navelement6 = document.getElementById("navelement6")
        navelement6.onmouseover = function () {
            navelement6.innerHTML = "連絡我們";
            navelement6.style.color = "red";
            navelement6.style.fontWeight = "bold"
            navelement6.style.fontSize = "23.52px"
            navelement6.style.letterSpacing = "4px"
        }
        navelement6.onmouseleave = function () {
            navelement6.innerHTML = "Contact Us";
            navelement6.style.color = "black";
            navelement6.style.fontWeight = "normal"
            navelement6.style.fontSize = "25px";
            navelement6.style.letterSpacing = "0px"

        }